server:
  port: 9003
spring:
  application: # eureka auth 服务名称
    name: eureka-mult-data-9003
  datasource:
    db1:
      jdbc-url: jdbc:mysql://1.1.1.1:13306/mult_db1?useSSL=false&characterEncoding=utf-8
      username: xxx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://1.1.1.1:13306/mult_db2?useSSL=false&characterEncoding=utf-8
      username: xxx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    hikari:
      #连接最长生命周期,当连接存活时间达到60s之后,会被关闭做退休处理 链接最大存活时间,比数据库的配置要小 ms
      max-lifetime: 60000
      #连接池中最小空闲连接数
      minimum-idle: 5
      #连接池中最大连接数
      maximum-pool-size: 15
      #是否自动提交
      auto-commit: true
      #链接允许最长空闲时间,如果连接空闲时间超过1分钟,则被关闭
      idle-timeout: 30000
      pool-name: BlogConfig
      #客户端创建连接等待超时时间,60秒内没有获取到连接抛异常,不再等待
      connection-timeout: 60000
      connection-init-sql: SELECT 1
      connection-test-query: select 1
  #sql语句
  # jpa 配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        #MySQL with InnoDB	org.hibernate.dialect.MySQLInnoDBDialect
        #MySQL with MyISAM	org.hibernate.dialect.MySQLMyISAMDialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #dialect: MySQL57InnoDB
    database: mysql
    generate-ddl: true
    open-in-view: false
    hibernate:
      #      更新或者创建表结构
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
logging:
  level:
    root: info
#配置加载